export enum RESOURCE_ACTIONS {
  GET_LIST = "GET_LIST",
  SET_LIST = "SET_LIST",
  GET_ONE = "GET_ONE",
  DELETE_ONE = "DELETE_ONE",
  DELETE_MANY = "DELETE_MANY",
  SAVE_ONE = "SAVE_ONE",
  SAVE_MANY = "SAVE_MANY",
}
